name: Test reusable

on:
  push:
    tags:
      - '**'

jobs:       
  reuse-job:
    environment: build  
    uses: ./.github/workflows/reusable.yml
    with:
      tag-list: '["${{ github.ref_name }}"]'
