name: test ref

on:
  workflow_dispatch:
    inputs:
      services:
        type: string

jobs:
  increment-tags:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: | 
          incrementedVersion="1.0.0"
          
          ref=${{ github.ref_name }}
          if [[ "$ref" != "develop" ]]; then
            refFragment=${ref##*/}
            refFragment=$( echo $refFragment | sed -e "s/-//g" )
            incrementedVersion=$incrementedVersion-$refFragment
          fi
          echo $incrementedVersion
